### ISSUE TITLE
Tab management

### ISSUE THREAD

**Issue by rayman89** [Adam42/pull-tabs#33]
I was wondering if you were willing to expand the addon so that you can manage tabs in bulk a bit more like for example being able to re arrange he tab order or reload tabs mute them copy their url to the clipboar move them to an other window or an existing window etc.

**Comment by Adam42** [comment]
The driving force behind this extension is to provide ways to remove tabs
that are not actively needed while still saving them somewhere for later.

I personally likely won't implement re-arranging, reloading or muting tabs
as those fall more into management than removal & storage. I'm not opposed
to merging in these features if you or someone else can implement them but
I likely won't have spare time to.

Actions are now loaded into the extension via Service Providers structure
https://github.com/Adam42/pull-tabs/tree/master/src/js/services

And I'm currently working on updating the options page to allow
enabling/disabling individual services/actions which would allow adding
those three features without impacting the current workflow.

I started work on adding a clipboard action last week
https://github.com/Adam42/pull-tabs/tree/feature/copy-to-clipboard/src/js/services
and plan to deploy that new action once I've updated the options page with
the enabling/disabling actions preference I noted above.

I hope to have both the updated options page and the clipboard action
deployed as part of the next release of this extension :)


On Dec 4, 2017 5:24 PM, "rayman89" <notifications@github.com> wrote:

I was wondering if you were willing to expand the addon so that you can
manage tabs in bulk a bit more like for example being able to re arrange he
tab order or reload tabs mute them copy their url to the clipboar move them
to an other window or an existing window etc.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Adam42/pull-tabs/issues/33>, or mute the thread

**Comment by rayman89** [comment]
Thank you.

**Comment by Adam42** [comment]
Added copy to clipboard in https://github.com/Adam42/pull-tabs/releases/tag/v0.13.0-beta and ability to enable/disable services. Made a card here https://github.com/Adam42/pull-tabs/projects/1 if someone wants to add new features.
